# Generated by Django 3.2.8 on 2021-11-13 20:25

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_total_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='cloudinary_public_id',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='cloudinary_secure_url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
