# Generated by Django 3.2.8 on 2021-11-13 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20211113_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-pk']},
        ),
    ]
