# Generated by Django 3.2.8 on 2021-10-28 18:48

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to=account.models.Profile.user_directory_path),
        ),
    ]
