version: '3'
services:
  sblog:
    build: .
    ports:
      - "8000:5000"
    env_file: .env-sblog
    restart: always
    links:
      - mysql:dbserver
  mysql:
    image: "mysql/mysql-server:5.7"
    env_file: .env-mysql
    restart: always
